### ISSUE TITLE
Fact Checker

### ISSUE THREAD

**Issue by coxley** [jhuntwv/test0#1]
`webpage.htm` states that you compete in juijitsu. This claim has been disputed by our fact checking bodies. Please correct your statements or be sentenced to death.

**Comment by jhuntwv** [comment]
Terrible oversight.  Putting out an urgent ticket to have this fixed.

**Comment by coxley** [comment]
Thanks for the prompt reply. I'm optimistic about our future collaboration.

**Comment by jhuntwv** [comment]
Issue resolved and merged.  Thank you for your time.
